# Generated by Django 4.1.1 on 2022-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000000000000000000)),
                ('bid_init', models.FloatField(verbose_name='bid')),
                ('image', models.URLField(verbose_name='image')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
