# Generated by Django 4.1.1 on 2022-09-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_description_comments_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='listing_bid',
        ),
        migrations.AddField(
            model_name='bidder',
            name='listing_bid',
            field=models.ManyToManyField(blank=True, related_name='bid', to='auctions.listing'),
        ),
    ]
