# Generated by Django 4.1.1 on 2022-09-28 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bidder_listing_bid_bidder_listing_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='listing_bid',
        ),
        migrations.AlterField(
            model_name='bidder',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
