# Generated by Django 4.1.1 on 2022-09-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bidder_listing_bid_alter_bidder_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='listing_bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to='auctions.listing'),
        ),
    ]
