# Generated by Django 4.1.1 on 2022-10-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_winner_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='winner',
            name='amt',
            field=models.FloatField(default=0, verbose_name='amount'),
            preserve_default=False,
        ),
    ]
